// components/layout.tsx
import Head from "next/head";
import Footer from "./footer";

/**
 * General layout of the website. Controls headers/footers shared between pages.
 * As well as general site styling (background, font, etc).
 */
export default function Layout({
  children,
  paddingTop = true,
}: {
  children: React.ReactNode;
  paddingTop?: boolean;
}) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="referrer" content="same-origin"></meta>
        <meta name="description" content="Chop trackers from shared link" />
        {/* @TODO: open graph tags */}
      </Head>
      <main className="mx-auto max-w-screen-md px-8 md:px-0">
        <div
          className={`flex min-h-screen flex-col${
            paddingTop ? " pt-[calc(10vh+4rem)]" : ""
          }`}
        >
          {children}
          <div className="invisible flex-grow"></div>
          <Footer />
        </div>
      </main>
    </>
  );
}

// src/lib/components/Layout.svelte
<script lang="ts">
  import Footer from "./Footer.svelte";

  interface Props {
    paddingTop?: boolean;
    children: import("svelte").Snippet;
  }

  let { paddingTop = true, children }: Props = $props();
</script>

<main class="mx-auto max-w-screen-md px-8 md:px-0">
  <div
    class={`flex min-h-screen flex-col ${paddingTop ? "pt-[calc(10vh+4rem)]" : ""}`}
  >
    {@render children()}
    <div class="invisible grow"></div>
    <Footer />
  </div>
</main>
